# @package _global_
TRAINER:
  gpus: ${SYSTEM.GPUS}
  distributed_backend: dp
  benchmark: ${SYSTEM.CUDNN.BENCHMARK}
  deterministic: ${SYSTEM.CUDNN.DETERMINISTIC}
  accumulate_grad_batches: 1
  profiler: False
  max_epochs: ${TRAIN.EPOCHS}
  log_save_interval: 100
  gradient_clip_val: 0 # 0.5
  num_sanity_val_steps: 2 # 0
  weights_summary: